title               : "Al-Salafiyyah"
description         : "Explore Islamic legal rulings issued by the scholars of the Sunnah and the Imam of the Salaf from among Ahlus-Sunnah wal-Jama'ah on worship, creed, bidah, family law and so many on. "
slogan              : "For Islamic Verdicts"
short_desc          : "A repository of Fatwas issued by the prominent scholars of Ahlus-Sunnah wal-jama'ah."
baseurl             : "/"
keywords            : "salafi, salaf, manhaj, islam, knowledge, shariah, muslim, islamic, fatwas, bidah, sunnah, muslimah, bid'ah, dawah, da'wah, lectures, arabic, sermon, musliman, community, ahlus sunnah wal jamaah, ahlus sunnah, sunnis, sunni, tawhid, tauhid, allah, prophets, prophet muhammad, rasul, rasulullah, muhammad, sahabah"
url                 : "https://alsalafiyyah.github.io"
author              : "Instagram@Alsalafiyyah"
contact:
  name              : "Instagram@Alsalafiyyah"
  email             : "alsalafiyyah@icloud.com"
safe                : true
future              : true
g_search_value      : "alsalafiyyah.github.io" # google search value
encoding            : "utf-8"
markdown_ext        : "markdown,mkdown,mkdn,mkd,md"
permalink           : pretty
markdown            : kramdown
highlighter         : rouge
locale              : ["en", "ar"]
defaultLang         : en
timezone            : Asia/Riyadh
github_username     : alsalafiyyah
git_repo            : alsalafiyyah.github.io
keep_files          : [images]
kramdown:
  syntax_highlighter_opts:
      disable : true

paginate            : 20
paginate_path       : "/fatwas/:num/"

webmaster_verifications: 
  google_site       : "K7QDv3cEwylAu_9fndO3ebQmNowxxRYCpqDEzQKQOy4" # google site verification
  bing              : "4F1A0A46CAA92F43191A0C4B37948DD7" # msvalidate.01
  yandex            : "ca07a6e68b1254db" # yandex verification
  domain_verify     : "6a0545495b6d882089f54152a3ef5f2c" # p:domain_verify
  analytics         : "G-QC20WKL1N2" # google analystic
  google-ads        : "ca-pub-1975848559090325" # google-adsense-account
  norton-safeweb    : "52A5Z1I99X-9SKMGBF3GZXFPIJW3M9OZNUFSIEUNQYQEAEY4KKQDC0HTSBPDJMUQL5H1EE8JK6-27UONEJJNQA1QHRAZKZWA3LRE3M19YL-LM7LW7HIO1EAW44XSXYH1" # norton-safeweb-site-verification
  email_webmaster   : "arubalessandra@gmail.com" 
  gsearch_id        : "86abb96a2158b40ed" # google search engine ID
  gtag_manager      : "G-QC20WKL1N2" # google tag
  wot-verification  : "5e71c40c8e8939cc0eb5" # web of trust

Tags                : '/tags/'
tag_page            : '/tags/'
Categories          : '/category/'
category_page       : '/category/'

# Manifest
manifest_name      : "Al-Salafiyyah"
manifest_desc      : "This site is dedicated to presenting the pure teachings of Islam and Sunnah, refuting bidahs, the lies and distortions."
manifest_lang      : "en_EN"
manifest_bg_color  : "#E5DCD7"
manifest_short_name: "Al-Salafiyyah"
manifest_display   : "standalone"

include:
  - _pages

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

exclude:
  - bin
  - tmp
  - .jekyll-cache
  - .jekyll-metadata
  - .sass-cache
  - config
  - vite.config.ts
  - Procfile.dev
  - Makefile
  - .gitignore
  - docs
  - README.md
  - README
  - LICENSE
  - CODE_OF_CONDUCT.md 
  - vendor
  - node_modules
  - Gemfile
  - Gemfile.lock
  - "sample*.png" 

defaults:
  # _posts
  - scope:
      path: "_posts/**"
      type: posts
    values:
      layout: post
      permalink: /:title/
  # _posts/audios/
  - scope:
      path: "_posts/audios/**"
      type: posts
    values:
      layout: post
      active: audios
      permalink: /audios/:title/
  # _posts/videos/    
  - scope:
      path: "_posts/videos/**"
      type: posts
    values:
      layout: post
      active: videos
      permalink: /videos/:title/
  # _posts/muqolat/
  - scope:
      path: "_posts/muqolat/**"
      type: posts
    values:
      layout: post
      permalink: /muqolat/:title/    
  # _posts/wahhabism/
  - scope:
      path: "_posts/wahhabism/**"
      type: posts
    values:
      layout: post
      permalink: /wahhabism/:title/
  # _posts/biography/
  - scope:
      path: "_posts/biography/**"
      type: posts
    values:
      layout: post
      permalink: /biography/:title/   
  # _pages
  - scope:
      path: "_pages"
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "Page"

# Collections
collections:
  fawaid:
    output: true
    permalink       : /:collection/:slug

# Alifta Scholars
group1:
  chairman: 
    - name: Shaykh Ibn Baz
      url: /biography/binbaz
  deputy_chairman:
    - name: Shaykh Abdul-Razzaq Afifi
      url: /biography/afifi
  members: 
    - name: Shaykh Abdullah ibn Ghudayyan
      url: /biography/ghudayyan
    - name: Shaykh Abdullah ibn Qa'ud
      url: /biography/qaud

group2:
  chairman: 
    - name: Shaykh Ibn Baz
      url: /biography/binbaz
  deputy_chairman:
    - name: Shaykh Abdul-Aziz Aal Al-Shaykh
      url: /biography/abdulaziz
  members: 
    - name: Shaykh Abdullah ibn Ghudayyan
      url: /biography/ghudayyan
    - name: Shaykh Salih Al-Fawzan
      url: /biography/fawzan
    - name: Shaykh Bakr Abu Zayd
      url: /biography/bakr

group3:
  chairman: 
    - name: Shaykh Ibn Baz
      url: /biography/binbaz
  deputy_chairman:
    - name: Shaykh Abdul-Razzaq Afifi
      url: /biography/afifi
  members: 
    - name: Shaykh Abdullah ibn Ghudayyan
      url: /biography/ghudayyan
    - name: Shaykh Abdullah ibn Mani'
      url: /biography/mani

group4:
  chairman: 
    - name: Shaykh Abdul-Razzaq Afifi
      url: /biography/afifi
  members: 
    - name: Shaykh Abdullah ibn Ghudayyan
      url: /biography/ghudayyan
    - name: Shaykh Abdullah ibn Mani'
      url: /biography/mani

group5:
  chairman: 
    - name: Shaykh Abdul-Aziz Aal Al-Shaykh
      url: /biography/abdulaziz
  members: 
    - name: Shaykh Abdullah ibn Ghudayyan
      url: /biography/ghudayyan
    - name: Shaykh Salih Al-Fawzan
      url: /biography/fawzan
    - name: Shaykh Bakr Abu Zayd
      url: /biography/bakr   

group6:
  chairman: 
    - name: Shaykh Ibn Baz
      url: /biography/binbaz
  deputy_chairman:
    - name: Shaykh Abdul-Razzaq Afifi
      url: /biography/afifi     
  members: 
    - name: Shaykh Abdullah ibn Ghudayyan
      url: /biography/ghudayyan   

group7:
  chairman: 
    - name: Shaykh Ibn Baz
      url: /biography/binbaz
  deputy_chairman:
    - name: Shaykh Abdul-Razzaq Afifi
      url: /biography/afifi
  members: 
    - name: Shaykh Abdullah ibn Ghudayyan
      url: /biography/ghudayyan
    - name: Shaykh Abdul-Aziz Aal Al-Shaykh
      url: /biography/abdulaziz      
    - name: Shaykh Salih Al-Fawzan
      url: /biography/fawzan
    - name: Shaykh Bakr Abu Zayd
      url: /biography/bakr

group8:
  chairman: 
    - name: Shaykh Ibn Baz
      url: /biography/binbaz
  members: 
    - name: Shaykh Abdullah ibn Ghudayyan
      url: /biography/ghudayyan

group9:
  chairman: 
    - name: Shaykh Ibn Baz
      url: /biography/binbaz
  deputy_chairman:
    - name: Shaykh Abdul-Razzaq Afifi
      url: /biography/afifi     
  members: 
    - name: Shaykh Abdullah ibn Qa'ud
      url: /biography/qaud   

group10:
  chairman: 
    - name: Shaykh Ibn Baz
      url: /biography/binbaz
  members: 
    - name: Shaykh Abdullah ibn Qa'ud
      url: /biography/qaud

group11:
  chairman: 
    - name: Shaykh Ibrahim ibn Muhammad Aal Al-Shaykh
      url: /biography/ibrahim
  deputy_chairman:
    - name: Shaykh Abdul-Razzaq Afifi
      url: /biography/afifi     
  members: 
    - name: Shaykh Abdullah ibn Sulayman Ibn Mani'
      url: /biography/mani   

group12:
  chairman: 
    - name: Shaykh Ibn Baz
      url: /biography/binbaz
  deputy_chairman:
    - name: Shaykh Abdul-Razzaq Afifi
      url: /biography/afifi

group13:
  chairman: 
    - name: Shaykh Ibn Baz
      url: /biography/binbaz
  members: 
    - name: Shaykh Abdul-Aziz Aal Al-Shaykh
      url: /biography/abdulaziz
    - name: Shaykh Salih Al-Fawzan
      url: /biography/fawzan
    - name: Shaykh Bakr Abu Zayd
      url: /biography/bakr   

