title               : "Al-Salafiyyah"
description         : "Explore Islamic legal rulings issued by the scholars of the Sunnah and the Imam of the Salaf from among Ahlus-Sunnah wal-Jama'ah on worship, creed, bidah, family law and so many on. "
slogan              : "For Islamic Verdicts"
short_desc          : "A repository of Fatwas issued by the prominent scholars of Ahlus-Sunnah."
baseurl             : "/"
keywords            : "salafi, salaf, manhaj, islam, knowledge, shariah, muslim, islamic, fatwas, bidah, sunnah, muslimah, bid'ah, dawah, da'wah, lectures, arabic, sermon, musliman, community, ahlus sunnah wal jamaah, ahlus sunnah, sunnis, sunni, tawhid, tauhid, allah, prophets, prophet muhammad, rasul, rasulullah, muhammad, sahabah"
url                 : "https://alsalafiyyah.github.io"
author              : "Instagram@Alsalafiyyah"
contact:
  name              : "Instagram@Alsalafiyyah"
  email             : "alsalafiyyah@icloud.com"
safe                : true
future              : true
g_search_value      : "alsalafiyyah.github.io" # google search value
encoding            : "utf-8"
markdown_ext        : "markdown,mkdown,mkdn,mkd,md"
permalink           : pretty
markdown            : kramdown
timezone            : Asia/Riyadh
github_username     : alsalafiyyah
git_repo            : alsalafiyyah.github.io

paginate            : 20
paginate_path       : "/fatwas/:num/"

webmaster_verifications: 
  google_site       : "K7QDv3cEwylAu_9fndO3ebQmNowxxRYCpqDEzQKQOy4" # google site verification
  bing              : "4F1A0A46CAA92F43191A0C4B37948DD7" # msvalidate.01
  yandex            : "ca07a6e68b1254db" # yandex verification
  domain_verify     : "6a0545495b6d882089f54152a3ef5f2c" # p:domain_verify
  analytics         : "G-QC20WKL1N2" # google analystic
  google-ads        : "ca-pub-1975848559090325" # google-adsense-account
  norton-safeweb    : "52A5Z1I99X-9SKMGBF3GZXFPIJW3M9OZNUFSIEUNQYQEAEY4KKQDC0HTSBPDJMUQL5H1EE8JK6-27UONEJJNQA1QHRAZKZWA3LRE3M19YL-LM7LW7HIO1EAW44XSXYH1" # norton-safeweb-site-verification
  email_webmaster   : "arubalessandra@gmail.com" 
  gsearch_id        : "86abb96a2158b40ed" # google search engine ID
  gtag_manager      : "G-QC20WKL1N2" # google tag
  wot-verification  : "5e71c40c8e8939cc0eb5" # web of trust

# Manifest
manifest_name      : "Al-Salafiyyah"
manifest_desc      : "This site is dedicated to presenting the pure teachings of Islam and Sunnah, refuting bidahs, the lies and distortions."
manifest_lang      : "en_EN"
manifest_bg_color  : "#E5DCD7"
manifest_short_name: "Al-Salafiyyah"
manifest_display   : "standalone"

categories_select: true

# Menu Navigation
menu_navigation:
  - title: Fatwas
    url: /fatwas/
  - title: Audios
    url: /audios/
  - title: Videos
    url: /videos/
  - title: Muqolat
    url: /muqolat/
  - title: "al-Qur'an"
    url: "/quran/"

# Footer Navigation
footer_navigation:
  - title: Instagram
    url: "https://instagram.com/alsalafiyyah"
  - title: About
    url: /about/
  - title: "عربي"
    url: /ar/

external_links:
  - name: "Shaykh Abdul-Aziz ibn Baz"
    url: "https://binbaz.org.sa/"
  - name: "Shaykh Salih ibn Fawzan al-Fawzan"
    url: "https://alfawzan.live/"
  - name: "Shaykh Muhammad ibn Salih al-'Uthaymeen"
    url: "https://binothaimeen.net/"
  - name: "Shaykh Abdul-Razzaq ibn Abdul-Muhsin al-Badr"
    url: "https://www.al-badr.net/"
  - name: "Shaykh Muqbil ibn Hadi al-Wadi'i"
    url: "https://www.muqbel.net/"
  - name: "Shaykh Muhammad Nasirudin al-Albani"
    url: "https://www.al-albany.com/"

# Site Elements
site_elements:
  published: "Published"
  next: "Newer"
  prev: "Older"
  last_modified: "Last Modified"
  share: "Spread"
  source: "Source"
  categories: "Categories"
  translator: "Translator"
  latest_posts: "Latest Fatwas"
  selected_post: "Selected Fatwa"
  recent_posts: "Recent Fatwas"
  read_more: "Read"
  view_all_posts: "View All Fatwas"
  classified_under: "Classified Under"
  taken_from: "Taken From"
  search: "Search"
  select_category: "Select Category"
  scholars: "Scholars"
  scholar: "Scholar"
  footer_slogan: "The Manhaj of The Salaf"
  related_fatwas: "Related Fatwas"
  most_read: "Most Read"
  home: "Home"
  subscribe_newsletter: "Subscribe to Our Newsletter"
  dir: "ltr"
  lang: "en"
  telegram: "Telegram"
  translation: "Arabic"
  translate: "Translation"
  contact_us: "Contact us"
  privacy_policy: "Privacy Policy"
  tos: "Terms of Service"
  all_rights_reserved: "All Rights Reserved"
  no_entries_found: "No entries found"
  search_results: "Search Result"
  all_entries: "All Entries"
  page_not_found: "Page not found"
  page_not_found_text: "The page you requested was not found."


include:
  - _pages

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

exclude:
  - bin
  - tmp
  - .jekyll-cache
  - .jekyll-metadata
  - .sass-cache
  - config
  - vite.config.ts
  - Procfile.dev
  - Makefile
  - .gitignore
  - docs
  - README.md
  - README
  - LICENSE
  - CODE_OF_CONDUCT.md 
  - vendor
  - node_modules
  - Gemfile
  - Gemfile.lock
  - "sample*.png" 

collections:
  categories:
    output: true
  tag:
    output: true
  books:
    output: true

defaults:
  # _posts
  - scope:
      path: "_posts/**"
      type: posts
    values:
      layout: post
      permalink: /:title/

  # _posts/audios/
  - scope:
      path: "_posts/audios/**"
      type: posts
    values:
      layout: post
      active: audios
      permalink: /audios/:title/
  - scope:
      path: "_posts/salih-ibn-fawzan/audios/**"
      type: posts
    values:
      layout: post
      permalink: /audios/:title/
  - scope:
      path: "_posts/ibn-uthaymeen/audios/**"
      type: posts
    values:
      layout: post
      permalink: /audios/:title/
  - scope:
      path: "_posts/ibn-baz/audios/**"
      type: posts
    values:
      layout: post
      permalink: /audios/:title/
  - scope:
      path: "_posts/abdul-muhsin/audios/**"
      type: posts
    values:
      layout: post
      permalink: /audios/:title/
  - scope:
      path: "_posts/albani/audios/**"
      type: posts
    values:
      layout: post
      permalink: /audios/:title/
  - scope:
      path: "_posts/muqbil-ibn-hadi/audios/**"
      type: posts
    values:
      layout: post
      permalink: /audios/:title/
  - scope:
      path: "_posts/muhammad-ibn-salih-luhaydan/audios/**"
      type: posts
    values:
      layout: post
      permalink: /audios/:title/
  
  # _posts/videos/    
  - scope:
      path: "_posts/videos/**"
      type: posts
    values:
      layout: post
      active: videos
      permalink: /videos/:title/
  - scope:
      path: "_posts/salih-ibn-fawzan/videos/**"
      type: posts
    values:
      layout: post
      permalink: /videos/:title/
  - scope:
      path: "_posts/ibn-uthaymeen/videos/**"
      type: posts
    values:
      layout: post
      permalink: /videos/:title/
  - scope:
      path: "_posts/ibn-baz/videos/**"
      type: posts
    values:
      layout: post
      permalink: /videos/:title/
 
  # _posts/muqolat/
  - scope:
      path: "_posts/muqolat/**"
      type: posts
    values:
      layout: post
      permalink: /muqolat/:title/   
  - scope:
      path: "_posts/salih-ibn-fawzan/**"
      type: posts
    values:
      layout: post
      permalink: /muqolat/:title/ 
  - scope:
      path: "_posts/ibn-baz/**"
      type: posts
    values:
      layout: post
      permalink: /muqolat/:title/ 
      
  # _posts/wahhabism/
  - scope:
      path: "_posts/wahhabism/**"
      type: posts
    values:
      layout: post
      permalink: /wahhabism/:title/
  # _posts/biography/
  - scope:
      path: "_posts/biography/**"
      type: posts
    values:
      layout: post
      permalink: /biography/:title/   
  # _categories
  - scope:
      path: "_categories"
      type: "categories"
    values:
      layout: "category"
      permalink: /category/:title/ 
  # _tag
  - scope:
      path: "_tag"
      type: "tag"
    values:
      layout: "tag"
      permalink: /scholars/:title/
  # _pages
  - scope:
      path: "_pages"
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# Alifta Scholars
group1:
  chairman: 
    - name: Shaykh Ibn Baz
      url: /biography/binbaz
  deputy_chairman:
    - name: Shaykh Abdul-Razzaq Afifi
      url: /biography/afifi
  members: 
    - name: Shaykh Abdullah ibn Ghudayyan
      url: /biography/ghudayyan
    - name: Shaykh Abdullah ibn Qa'ud
      url: /biography/qaud

group2:
  chairman: 
    - name: Shaykh Ibn Baz
      url: /biography/binbaz
  deputy_chairman:
    - name: Shaykh Abdul-Aziz Aal Al-Shaykh
      url: /biography/abdulaziz
  members: 
    - name: Shaykh Abdullah ibn Ghudayyan
      url: /biography/ghudayyan
    - name: Shaykh Salih Al-Fawzan
      url: /biography/fawzan
    - name: Shaykh Bakr Abu Zayd
      url: /biography/bakr

group3:
  chairman: 
    - name: Shaykh Ibn Baz
      url: /biography/binbaz
  deputy_chairman:
    - name: Shaykh Abdul-Razzaq Afifi
      url: /biography/afifi
  members: 
    - name: Shaykh Abdullah ibn Ghudayyan
      url: /biography/ghudayyan
    - name: Shaykh Abdullah ibn Muni'
      url: /biography/mani

group4:
  chairman: 
    - name: Shaykh Abdul-Razzaq Afifi
      url: /biography/afifi
  members: 
    - name: Shaykh Abdullah ibn Ghudayyan
      url: /biography/ghudayyan
    - name: Shaykh Abdullah ibn Muni'
      url: /biography/mani

group5:
  chairman: 
    - name: Shaykh Abdul-Aziz Aal Al-Shaykh
      url: /biography/abdulaziz
  members: 
    - name: Shaykh Abdullah ibn Ghudayyan
      url: /biography/ghudayyan
    - name: Shaykh Salih Al-Fawzan
      url: /biography/fawzan
    - name: Shaykh Bakr Abu Zayd
      url: /biography/bakr   

group6:
  chairman: 
    - name: Shaykh Ibn Baz
      url: /biography/binbaz
  deputy_chairman:
    - name: Shaykh Abdul-Razzaq Afifi
      url: /biography/afifi     
  members: 
    - name: Shaykh Abdullah ibn Ghudayyan
      url: /biography/ghudayyan   

group7:
  chairman: 
    - name: Shaykh Ibn Baz
      url: /biography/binbaz
  deputy_chairman:
    - name: Shaykh Abdul-Razzaq Afifi
      url: /biography/afifi
  members: 
    - name: Shaykh Abdullah ibn Ghudayyan
      url: /biography/ghudayyan
    - name: Shaykh Abdul-Aziz Aal Al-Shaykh
      url: /biography/abdulaziz      
    - name: Shaykh Salih Al-Fawzan
      url: /biography/fawzan
    - name: Shaykh Bakr Abu Zayd
      url: /biography/bakr

group8:
  chairman: 
    - name: Shaykh Ibn Baz
      url: /biography/binbaz
  members: 
    - name: Shaykh Abdullah ibn Ghudayyan
      url: /biography/ghudayyan

group9:
  chairman: 
    - name: Shaykh Ibn Baz
      url: /biography/binbaz
  deputy_chairman:
    - name: Shaykh Abdul-Razzaq Afifi
      url: /biography/afifi     
  members: 
    - name: Shaykh Abdullah ibn Qa'ud
      url: /biography/qaud   

group10:
  chairman: 
    - name: Shaykh Ibn Baz
      url: /biography/binbaz
  members: 
    - name: Shaykh Abdullah ibn Qa'ud
      url: /biography/qaud

group11:
  chairman: 
    - name: Shaykh Ibrahim ibn Muhammad Aal Al-Shaykh
      url: /biography/ibrahim
  deputy_chairman:
    - name: Shaykh Abdul-Razzaq Afifi
      url: /biography/afifi     
  members: 
    - name: Shaykh Abdullah ibn Sulayman Ibn Muni'
      url: /biography/mani   

group12:
  chairman: 
    - name: Shaykh Ibn Baz
      url: /biography/binbaz
  deputy_chairman:
    - name: Shaykh Abdul-Razzaq Afifi
      url: /biography/afifi

group13:
  chairman: 
    - name: Shaykh Ibn Baz
      url: /biography/binbaz
  members: 
    - name: Shaykh Abdul-Aziz Aal Al-Shaykh
      url: /biography/abdulaziz
    - name: Shaykh Salih Al-Fawzan
      url: /biography/fawzan
    - name: Shaykh Bakr Abu Zayd
      url: /biography/bakr   

group14:
  chairman: 
    - name: Shaykh Abdul-Aziz ibn Baz
      url: /biography/binbaz/
  members: 
    - name: Shaykh Abdul-Aziz Aal Al-Shaykh
      url: /biography/abdulaziz/
    - name: Shaykh Abdullah ibn Ghudayyan
      url: /biography/ghudayyan/
    - name: Shaykh Salih Fawzan
      url: /biography/fawzan/
    - name: Shaykh Bakr Abu Zayd
      url: /biography/bakr/

group15:
  chairman: 
    - name: Shaykh Ibn Baz
      url: /biography/binbaz/
  members: 
    - name: Shaykh Abdul-Aziz Aal Al-Shaykh
      url: /biography/abdulaziz/
    - name: Shaykh Salih Al-Fawzan
      url: /biography/fawzan/

group16:
  chairman: 
    - name: Shaykh Abdul-Aziz Aal Al-Shaykh
      url: /biography/abdulaziz/
  deputy_chairman:
    - name: Shaykh Abdul-Razzaq Al-Afifi
      url: /biography/afifi/
  members: 
    - name: Shaykh Abdullah ibn Ghudayyan
      url: /biography/ghudayyan/
    - name: Shaykh Salih Fawzan
      url: /biography/fawzan/
    - name: Shaykh Bakr Abu Zayd
      url: /biography/bakr/

group17:
  chairman: 
    - name: Abdul-Aziz ibn Abdullah Aal Al-Shaykh
      url: /biography/abdulaziz/
  members: 
    - name: Shaykh Salih Fawzan
      url: /biography/fawzan/
    - name: Shaykh Bakr ibn Abdullah Abu Zayd
      url: /biography/bakr/

group18:
  chairman: 
    - name: Shaykh Abdul-Aziz Ibn Baz
      url: /biography/binbaz/
  members:
    - name: Shaykh Abdullah Ibn Ghudayyan
      url: /biography/ghudayyan/
    - name: Shaykh Abdullah Ibn Qa'ud
      url: /biography/qaud/

group19:
  chairman: 
    - name: Shaykh Ibn Baz
      url: /biography/binbaz
  deputy_chairman:
    - name: Shaykh Abdul-Razzaq Afifi
      url: /biography/afifi
  members:
    - name: Shaykh Abdul-Aziz Aal Al-Shaykh
      url: /biography/abdulaziz      
    - name: Shaykh Salih Al-Fawzan
      url: /biography/fawzan
    - name: Shaykh Bakr Abu Zayd
      url: /biography/bakr

group20:
  chairman: 
    - name: Shaykh Salih al-Fawzan
      url: /biography/fawzan
  members: 
    - name: Shaykh Muhammad ibn hasan 
      url: /biography/muhammad-ibn-hasan
    - name: Shaykh Saad ibn Naseer
      url: /biography/saad-ibn-naseer
    - name: Shaykh Abdul Salam ibn Abdullah
      url: /biography/abdul-salam   


