nav:
  - name: Fatwas
    url: /fatwas
    active: fatwas
  - name: Audios
    url: /audios
    active: audios
  - name: Muqolat
    url: /muqolat
    active: muqolat
  - name: Categories
    url: /category
    active: category
  - name: Bid'ah
    url: /bidah/
  - name: Wahhabism
    url: /Wahhabism/

footer:
  - name: Sitemap
    url: /sitemap
  - name: RSS Feed
    url: /feed   
  - name: Instagram
    url: https://instagram.com/alsalafiyyah
  - name: AlFatawa.Com
    url: https://al-fatawa.com/

page: 
  NoFatwas: "There are no fatwas for this topic."
  chairman: Chairman
  deputy_chairman: Deputy Chairman
  members: Members
  mufti: Mufti
  shaykh: Shaykh
  notFoundtitle: Page not found
  404: "Page not found. The page you are looking for is either under construction or is temporarily not available."
  fatwas: Fatwas
  audios: Audios
  categories: Categories
  next: Next
  prev: Prev
  home: Home
  books: Books
  edit: Edit on GitHub
  search: Search
  created_at: Creadted at
  last_updated: Last updated
  ref: Reference(s)
  source: Source(s)
  muftis: Mufti(s)

links:
  - name: Wahhabism
    url: /wahabism
  - name: Scholars
    url: /salafi-scholars
  - name: Refutals
    url: /refutals
  - name: Muqolat
    url: /muqolat
  - name: Categories
    url: /category
  - name: Books
    url: /books
  - name: The Sects
    url: /the-sects
  - name: Scholars Biography
    url: /biography
  - name: Audios
    url: /audios
  - name: Fatwas
    url: /fatwas
  - name: Fawaid
    url: /fawaid


faq_1: >
  Salafiyyah is a term derived from the word “Salaf”, 
  which refers to the righteous predecessors of 
  the first three generations of Muslims which include 
  the Sahabah (Companions of the Prophet), Tabi‘un 
  (Followers, the generation after the Companions of 
  the Prophet) and Tabi‘ Al-Tabi‘un (Successors, the 
  generation after the Tabi‘un). <a href="">read more</a>
faq_2: >
  The word “Salafis” is the plural of “Salafi”, derived 
  from “Salaf” that has the above-mentioned meaning. It 
  refers to those following the way of the Salaf 
  (righteous predecessors) of the early Muslim generation 
  in their adherence to the Qur‘an and the Sunnah and 
  calling people to believe and act upon them, and thereby 
  became known as “Ahlus-Sunnah wal-Jama'ah.”
  
