nav:
  - name: Fatwas
    url: /fatwas
    active: fatwas
  - name: Audios
    url: /audios
    active: audios
  - name: Muqolat
    url: /muqolat
    active: muqolat
  - name: Categories
    url: /category
    active: category

footer:
  - name: Sitemap
    url: /sitemap
  - name: Instagram
    url: https://instagram.com/alsalafiyyah

page: 
  NoFatwas: "There are no fatwas for this topic."
  chairman: Chairman
  deputy_chairman: Deputy Chairman
  members: Members
  mufti: Mufti
  shaykh: Shaykh
  notFoundtitle: Page not found
  404: "Page not found. The page you are looking for is either under construction or is temporarily not available."
  fatwas: Fatwas
  audios: Audios
  categories: Categories
  next: Next
  prev: Prev
  home: Home
  books: Books
  edit: Edit on GitHub
  search: Search


