name: Deploy Jekyll site to Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1 # Using v1 tag is more stable and faster than specific commit SHAs
        with:
          ruby-version: '3.2'
          bundler-cache: true
          # Increasing this only if gems get corrupted
          cache-version: 1 

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build with Jekyll
        # Added --profile to help you see slow pages and --trace for error debugging
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}" --profile
        env:
          JEKYLL_ENV: production
          # Speed up Liquid rendering by telling Ruby to use more memory for GC
          RUBY_GC_HEAP_FREE_SLOTS: 600000

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
