name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Jekyll Builder for GitHub Pages
      uses: fabacab/jekyll-builder-for-github-pages-action@v1

